stages:
- stage: Deploy
  displayName: Deploy Stage

  jobs:
  - deployment: DeployToVM
    displayName: Deploy to Linux VM
    environment: "DevOps Environment"

    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - script: |
              echo "Hello from Azure DevOps VM!"
              whoami
              hostname
              pwd
              ls -la
            displayName: "Verify Deployment"
