trigger: none

pool:
  vmImage: ubuntu-latest
  
stages:
- stage: Deploy
  displayName: Install Jenkins

  jobs:
  - deployment: InstallJenkins
    displayName: Install Jenkins on Linux VM
    environment: "DevOps Environment"

    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self

          - script: |
              echo "Updating packages..."
              sudo apt-get update -y

              echo "Installing Java..."
              sudo apt-get install -y fontconfig openjdk-17-jdk

              java -version

              echo "Adding Jenkins repository..."
              curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
              /usr/share/keyrings/jenkins-keyring.asc > /dev/null

              echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
              https://pkg.jenkins.io/debian-stable binary/" | sudo tee \
              /etc/apt/sources.list.d/jenkins.list > /dev/null

              sudo apt-get update -y

              echo "Installing Jenkins..."
              sudo apt-get install -y jenkins

              echo "Starting Jenkins..."
              sudo systemctl enable jenkins
              sudo systemctl start jenkins

              echo "Checking Jenkins Status..."
              sudo systemctl status jenkins --no-pager

              echo "Jenkins Version:"
              jenkins --version || true

              echo "Initial Admin Password:"
              sudo cat /var/lib/jenkins/secrets/initialAdminPassword

            displayName: "Install Jenkins"
